apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
data:
  access-token: "DO_API_TOKEN_BASE64"
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-stage
  namespace: default
spec:
  acme:
    email: example@example.org
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-stage
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com
  namespace: default
spec:
  secretName: example-com-tls
  issuerRef:
    name: letsencrypt-stage
  dnsNames:
  - '*.example.com'
  - 'example.com'

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: default
spec:
  acme:
    email: example@example.org
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token
